import type { NavSection, OverviewRow, WebGuide } from './types'

export const categoryMeta = {
  base: { label: '页面基础', className: 'tag-base' },
  language: { label: '编程语言', className: 'tag-language' },
  engineering: { label: '工程化', className: 'tag-engineering' },
  network: { label: '前端网络', className: 'tag-network' },
  framework: { label: '框架生态', className: 'tag-framework' },
  miniapp: { label: '小程序', className: 'tag-miniapp' },
} as const

export const webGuides: WebGuide[] = [
  {
    id: 'html-css',
    name: 'HTML & CSS',
    shortName: 'HTML/CSS',
    icon: '🎨',
    iconClass: 'icon-htmlcss',
    navIconBg: '#4a2f14',
    category: 'base',
    categoryLabel: '页面基础',
    sectionTitle: '🎨 页面基础',
    subtitle: '前端页面结构与视觉表现的根基，决定你能否准确还原设计稿',
    frequency: 5,
    difficulty: 2,
    periodWeeks: '3–4 周',
    periodDescription: '3–4 周（先建立页面结构与布局直觉）',
    remark: '前端第一站，必须扎实',
    learningOutline: [
      { title: 'HTML 语义化', items: ['文档结构', '语义标签', '表单', '可访问性'] },
      { title: 'CSS 基础', items: ['选择器', '盒模型', '继承层叠', '单位'] },
      { title: '布局系统', items: ['Flex', 'Grid', '定位', '响应式'] },
      { title: '视觉表现', items: ['字体', '颜色', '阴影', '动画过渡'] },
      { title: '移动端适配', items: ['viewport', 'rem/vw', '媒体查询', '安全区'] },
      { title: '页面实战', items: ['登录页', '列表页', '后台布局', '官网首页'] },
    ],
    coreTopics: ['HTML5 语义化标签与文档结构', '表单控件、校验与基础可访问性', 'CSS 盒模型、选择器优先级、BFC', 'Flex 与 Grid 两套核心布局方案', '响应式布局、移动端适配与媒体查询', 'CSS 动画、transition、transform', '常见页面结构：导航、卡片、表格、表单、弹窗', '浏览器默认样式与 CSS Reset / Normalize', '设计稿还原与像素级调试', '基础可维护 CSS 命名规范'],
    books: [
      { name: '《HTML5与CSS3基础教程》', description: '适合零基础建立页面结构与样式能力' },
      { name: '《CSS世界》', description: '张鑫旭著 · 深入理解 CSS 细节与布局机制' },
    ],
    sites: [
      { url: 'https://developer.mozilla.org/zh-CN/docs/Web/HTML', description: 'MDN HTML 中文文档' },
      { url: 'https://developer.mozilla.org/zh-CN/docs/Web/CSS', description: 'MDN CSS 中文文档' },
      { url: 'https://web.dev/learn/css/', description: 'Google Web.dev CSS 系统教程' },
    ],
    tip: '💡 不要只背属性。建议每学一个布局知识，就立刻用它还原一个真实页面模块。',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    shortName: 'JavaScript',
    icon: '✨',
    iconClass: 'icon-js',
    navIconBg: '#4a3d08',
    category: 'language',
    categoryLabel: '编程语言',
    sectionTitle: '✨ 编程语言',
    subtitle: '前端核心编程语言，连接页面、数据、交互与工程体系',
    frequency: 5,
    difficulty: 4,
    periodWeeks: '6–8 周',
    periodDescription: '6–8 周（前端能力分水岭）',
    remark: '前端最核心能力',
    learningOutline: [
      { title: '语言基础', items: ['变量', '类型', '运算符', '流程控制'] },
      { title: '函数与对象', items: ['作用域', '闭包', 'this', '原型链'] },
      { title: 'DOM/BOM', items: ['节点操作', '事件机制', '浏览器对象', '表单交互'] },
      { title: '异步编程', items: ['回调', 'Promise', 'async/await', '事件循环'] },
      { title: 'ES6+', items: ['模块化', '解构', '迭代器', 'Class'] },
      { title: '实战沉淀', items: ['Todo', '轮播图', '请求封装', '工具函数库'] },
    ],
    coreTopics: ['JavaScript 数据类型、隐式转换与类型判断', '函数、作用域链、闭包与执行上下文', '对象、原型、原型链与继承', 'this 指向、call/apply/bind', 'DOM 查询、事件委托与事件传播', 'Promise、async/await 与异常处理', '事件循环、宏任务、微任务', 'ES Module 模块化', '数组、对象、字符串常用 API', '防抖、节流、深拷贝等高频工具函数'],
    books: [
      { name: '《JavaScript高级程序设计》', description: '红宝书 · 系统全面，适合打基础' },
      { name: '《你不知道的JavaScript》', description: '深入作用域、this、对象与异步机制' },
    ],
    sites: [
      { url: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript', description: 'MDN JavaScript 中文文档' },
      { url: 'https://javascript.info/', description: '现代 JavaScript 教程' },
      { url: 'https://zh.javascript.info/', description: '现代 JavaScript 教程中文版' },
    ],
    note: '📌 JavaScript 是后续 Vue、React、工程化的前置基础。框架可以先会用，但 JS 基础决定上限。',
  },
  {
    id: 'engineering',
    name: '前端工程化',
    shortName: '工程化',
    icon: '🧰',
    iconClass: 'icon-engineering',
    navIconBg: '#123a4a',
    category: 'engineering',
    categoryLabel: '工程化',
    sectionTitle: '🧰 工程能力',
    subtitle: '把零散页面开发升级为可维护、可构建、可协作、可部署的现代项目',
    frequency: 4,
    difficulty: 4,
    periodWeeks: '4–6 周',
    periodDescription: '4–6 周（配合 Vue/React 项目一起学）',
    remark: '现代前端必备',
    learningOutline: [
      { title: '开发环境', items: ['Node.js', 'npm/pnpm', '包管理', '脚本命令'] },
      { title: '模块化', items: ['ESM', 'CommonJS', '路径别名', '依赖管理'] },
      { title: '构建工具', items: ['Vite', 'Webpack', 'Babel', 'PostCSS'] },
      { title: '代码质量', items: ['TypeScript', 'ESLint', 'Prettier', 'Git Hooks'] },
      { title: '项目规范', items: ['目录结构', '组件规范', '环境变量', '提交规范'] },
      { title: '部署发布', items: ['打包', '静态部署', 'CI/CD', '性能分析'] },
    ],
    coreTopics: ['Node.js 与 npm/pnpm/yarn 包管理', 'package.json scripts 与依赖版本管理', 'ES Module、CommonJS 与 Tree Shaking', 'Vite 项目结构、开发服务器、生产构建', 'Webpack 基础概念：entry、loader、plugin、chunk', 'TypeScript 基础类型、接口、泛型与 Vue/React 结合', 'ESLint、Prettier、EditorConfig 统一代码风格', '环境变量、代理配置、路径别名', 'Git 分支、提交规范与团队协作', '静态资源部署、缓存策略与构建产物分析'],
    books: [
      { name: '《深入浅出Webpack》', description: '系统理解传统构建工具核心概念' },
      { name: '《TypeScript编程》', description: '建立类型系统思维，提升项目可维护性' },
    ],
    sites: [
      { url: 'https://cn.vitejs.dev/', description: 'Vite 中文文档' },
      { url: 'https://webpack.js.org/concepts/', description: 'Webpack 官方概念文档' },
      { url: 'https://www.typescriptlang.org/docs/', description: 'TypeScript 官方文档' },
    ],
    tip: '💡 工程化不要孤立学。最好用一个真实项目不断加入 TypeScript、Lint、构建、部署等能力。',
  },
  {
    id: 'network',
    name: '前端网络',
    shortName: '前端网络',
    icon: '🌐',
    iconClass: 'icon-network',
    navIconBg: '#123a2a',
    category: 'network',
    categoryLabel: '前端网络',
    sectionTitle: '🌐 网络与浏览器',
    subtitle: '理解浏览器如何请求数据、缓存资源、保障安全，是前后端联调与性能优化的基础',
    frequency: 4,
    difficulty: 3,
    periodWeeks: '3–4 周',
    periodDescription: '3–4 周（和接口联调一起学效果最好）',
    remark: '联调与性能优化基础',
    learningOutline: [
      { title: 'HTTP 基础', items: ['URL', '请求方法', '状态码', 'Header'] },
      { title: '数据请求', items: ['fetch', 'axios', '拦截器', '错误处理'] },
      { title: '跨域与安全', items: ['CORS', 'Cookie', 'Token', 'XSS/CSRF'] },
      { title: '缓存机制', items: ['强缓存', '协商缓存', 'Service Worker', 'CDN'] },
      { title: '实时通信', items: ['WebSocket', 'SSE', '轮询', '心跳'] },
      { title: '性能排查', items: ['DevTools', '瀑布图', '首屏优化', '资源压缩'] },
    ],
    coreTopics: ['HTTP/HTTPS 基本流程、请求方法与状态码', '请求头、响应头、Content-Type、Accept', 'fetch 与 axios 请求封装', '统一错误处理、取消请求、重试策略', '浏览器同源策略与 CORS', 'Cookie、Session、JWT 与登录态维护', 'XSS、CSRF、点击劫持等基础安全问题', '浏览器缓存：强缓存、协商缓存', 'WebSocket、SSE 与实时消息', 'Chrome DevTools Network 面板排查问题'],
    books: [
      { name: '《图解HTTP》', description: '用图解方式理解 HTTP 基础，非常适合入门' },
      { name: '《Web性能权威指南》', description: '深入理解网络、浏览器与性能优化' },
    ],
    sites: [
      { url: 'https://developer.mozilla.org/zh-CN/docs/Web/HTTP', description: 'MDN HTTP 中文文档' },
      { url: 'https://web.dev/learn/performance/', description: 'Web.dev 性能学习路径' },
      { url: 'https://axios-http.com/docs/intro', description: 'Axios 官方文档' },
    ],
  },
  {
    id: 'vue',
    name: 'Vue',
    shortName: 'Vue',
    icon: '🟢',
    iconClass: 'icon-vue',
    navIconBg: '#103a2a',
    category: 'framework',
    categoryLabel: '框架生态',
    sectionTitle: '🟢 框架生态',
    subtitle: '渐进式前端框架，适合快速构建中后台、管理系统与业务应用',
    frequency: 5,
    difficulty: 3,
    periodWeeks: '5–7 周',
    periodDescription: '5–7 周（从响应式到项目实战）',
    remark: '国内业务开发高频',
    learningOutline: [
      { title: '响应式基础', items: ['ref/reactive', 'computed', 'watch', '生命周期'] },
      { title: '模板语法', items: ['插值', '指令', '事件', '表单绑定'] },
      { title: '组件化', items: ['Props', 'Emits', 'Slots', '组合式 API'] },
      { title: 'Vue 路由', items: ['路由配置', '动态路由', '导航守卫', '权限路由'] },
      { title: '状态管理', items: ['Pinia', '持久化', '模块拆分', '异步状态'] },
      { title: 'Vue 项目', items: ['Element Plus', '接口封装', '权限系统', '打包部署'] },
    ],
    coreTopics: ['Vue 3 响应式系统与 Composition API', '模板语法、指令、事件与表单绑定', '组件通信：props、emit、provide/inject', '插槽、动态组件、异步组件', 'Vue Router 路由配置、嵌套路由、导航守卫', 'Pinia 状态管理与持久化', '请求封装、权限控制、菜单路由生成', 'Element Plus / Ant Design Vue 组件库使用', 'Vue 项目目录结构与工程规范', '性能优化：keep-alive、懒加载、拆包'],
    books: [
      { name: '《Vue.js设计与实现》', description: '深入理解 Vue 响应式与渲染机制' },
      { name: '《Vue.js实战》', description: '适合从基础过渡到项目实践' },
    ],
    sites: [
      { url: 'https://cn.vuejs.org/', description: 'Vue 官方中文文档' },
      { url: 'https://router.vuejs.org/zh/', description: 'Vue Router 官方中文文档' },
      { url: 'https://pinia.vuejs.org/zh/', description: 'Pinia 官方中文文档' },
    ],
    tip: '💡 Vue 学习顺序建议：响应式 → 模板 → 组件 → 路由 → 状态管理 → 中后台项目。',
  },
  {
    id: 'react',
    name: 'React',
    shortName: 'React',
    icon: '⚛️',
    iconClass: 'icon-react',
    navIconBg: '#12334a',
    category: 'framework',
    categoryLabel: '框架生态',
    subtitle: '组件化 UI 库，生态庞大，适合复杂交互、跨端和大型前端应用',
    frequency: 4,
    difficulty: 4,
    periodWeeks: '5–7 周',
    periodDescription: '5–7 周（重视函数式思维与 Hooks）',
    remark: '大厂与复杂应用常见',
    learningOutline: [
      { title: 'JSX 与组件', items: ['JSX', '函数组件', 'Props', '条件渲染'] },
      { title: '状态与事件', items: ['useState', '事件处理', '表单', '列表渲染'] },
      { title: 'Hooks', items: ['useEffect', 'useMemo', 'useCallback', '自定义 Hook'] },
      { title: '路由与状态', items: ['React Router', 'Redux Toolkit', 'Zustand', 'Context'] },
      { title: '工程生态', items: ['Vite React', 'Next.js', 'Ant Design', '测试'] },
      { title: '项目实战', items: ['后台系统', '权限控制', '性能优化', '部署上线'] },
    ],
    coreTopics: ['JSX 语法与函数组件', 'props、state、事件处理与受控组件', '列表渲染、条件渲染、组件拆分', 'Hooks：useState、useEffect、useRef、useMemo、useCallback', '自定义 Hook 与逻辑复用', 'React Router 路由管理', 'Redux Toolkit / Zustand 状态管理', 'React 性能优化：memo、懒加载、虚拟列表', 'Next.js 基础与 SSR/SSG 概念', 'React + TypeScript 项目实践'],
    books: [
      { name: '《React学习手册》', description: '系统掌握 React 基础与现代写法' },
      { name: '《深入React技术栈》', description: '适合进阶理解 React 原理与生态' },
    ],
    sites: [
      { url: 'https://react.dev/', description: 'React 官方文档' },
      { url: 'https://reactrouter.com/en/main', description: 'React Router 官方文档' },
      { url: 'https://redux-toolkit.js.org/', description: 'Redux Toolkit 官方文档' },
    ],
    note: '📌 如果已经会 Vue，学 React 时重点切换思维：JSX、Hooks、不可变数据、函数式组件。',
  },
  {
    id: 'miniapp',
    name: '小程序',
    shortName: '小程序',
    icon: '📱',
    iconClass: 'icon-miniapp',
    navIconBg: '#164a1f',
    category: 'miniapp',
    categoryLabel: '小程序',
    sectionTitle: '📱 跨端应用',
    subtitle: '微信/支付宝等平台轻应用形态，适合业务闭环、工具应用与移动端场景',
    frequency: 3,
    difficulty: 3,
    periodWeeks: '3–5 周',
    periodDescription: '3–5 周（建议已有 Vue/React 基础后学习）',
    remark: '移动业务常用补充',
    learningOutline: [
      { title: '平台基础', items: ['项目结构', '页面配置', '生命周期', '开发者工具'] },
      { title: '视图与样式', items: ['WXML', 'WXSS', '组件', 'rpx 适配'] },
      { title: '交互与数据', items: ['事件', 'setData', '表单', '列表渲染'] },
      { title: '能力调用', items: ['登录', '授权', '支付', '上传下载'] },
      { title: '工程框架', items: ['uni-app', 'Taro', '跨端组件', '条件编译'] },
      { title: '项目发布', items: ['分包', '性能优化', '审核发布', '监控'] },
    ],
    coreTopics: ['小程序项目结构、页面配置与 app.json', 'WXML、WXSS、组件与 rpx 适配', '页面生命周期与组件生命周期', '事件绑定、setData 与数据更新机制', '登录授权、用户信息、接口请求', '文件上传下载、地理位置、扫码、支付等平台能力', '分包加载、预加载与性能优化', '小程序发布流程与审核注意事项', 'uni-app / Taro 跨端开发思路', '小程序与 H5、App 的差异'],
    books: [
      { name: '《微信小程序开发入门与实践》', description: '适合了解原生小程序开发流程' },
      { name: '《uni-app 跨平台开发实战》', description: '适合需要一套代码多端发布的场景' },
    ],
    sites: [
      { url: 'https://developers.weixin.qq.com/miniprogram/dev/framework/', description: '微信小程序官方框架文档' },
      { url: 'https://uniapp.dcloud.net.cn/', description: 'uni-app 官方文档' },
      { url: 'https://docs.taro.zone/docs/', description: 'Taro 官方文档' },
    ],
    tip: '💡 小程序建议放在 Vue/React 之后学：先理解组件化与状态，再适应平台限制和跨端差异。',
  },
]

export const navSections: NavSection[] = [
  { title: '基础入门', items: webGuides.filter((item) => item.category === 'base' || item.category === 'language') },
  { title: '工程与网络', items: webGuides.filter((item) => item.category === 'engineering' || item.category === 'network') },
  { title: '框架生态', items: webGuides.filter((item) => item.category === 'framework') },
  { title: '跨端应用', items: webGuides.filter((item) => item.category === 'miniapp') },
]

export const overviewRows: OverviewRow[] = webGuides.map(({ category, shortName, frequency, difficulty, periodWeeks, remark }) => ({
  category,
  name: shortName,
  frequency,
  difficulty,
  period: periodWeeks,
  remark,
}))

export const heroStats = [
  { value: webGuides.length, label: '学习模块' },
  { value: '6', label: '能力类型' },
  { value: '32-45', label: '学习周数' },
  { value: '20+', label: '推荐资源' },
]

export const learningRoute = webGuides.map((item) => ({ id: item.id, label: item.shortName, icon: item.icon }))
