import type { NavSection, OverviewRow, TechGuide } from './types'

export const categoryMeta = {
  web: { label: 'Web框架', className: 'tag-web' },
  db: { label: '数据库', className: 'tag-db' },
  cache: { label: '缓存', className: 'tag-cache' },
  build: { label: '构建工具', className: 'tag-build' },
  container: { label: '容器', className: 'tag-container' },
  mq: { label: '消息队列', className: 'tag-mq' },
} as const

export const techGuides: TechGuide[] = [
  {
    id: 'spring',
    name: 'Spring Framework',
    shortName: 'Spring',
    icon: '🌿',
    iconClass: 'icon-spring',
    navIconBg: '#2d4a22',
    category: 'web',
    categoryLabel: 'Web框架',
    sectionTitle: '🌿 Web框架',
    subtitle: '企业级 Java 应用开发的核心框架，贯穿整个后端生态',
    frequency: 5,
    difficulty: 5,
    periodWeeks: '10–14 周',
    periodDescription: '10–14 周（重点框架，充分投入）',
    remark: '最核心框架，优先掌握',
    learningOutline: [
      { title: '基础准备', items: ['Java 反射', '注解', '设计模式', 'Maven 基础'] },
      { title: 'IoC 容器', items: ['Bean 生命周期', '依赖注入', '作用域', '配置方式'] },
      { title: 'AOP 编程', items: ['代理模式', '切点表达式', '通知类型', '事务切面'] },
      { title: '事务与数据访问', items: ['声明式事务', '传播行为', '隔离级别', 'JdbcTemplate'] },
      { title: 'Spring MVC', items: ['请求流程', 'Controller', '参数绑定', '拦截器'] },
      { title: '源码与实战', items: ['容器启动流程', 'BeanFactory', 'ApplicationContext', '小型 Web 项目'] },
    ],
    coreTopics: ['IoC 容器与依赖注入（DI）原理与实践', '面向切面编程（AOP）—— 日志、事务、安全切面', 'Spring MVC —— DispatcherServlet、控制器、视图解析', 'Spring Data —— JPA、Repository 抽象层', 'Spring Security —— 认证、授权、JWT 集成', 'Spring Transaction —— 声明式事务、传播机制、隔离级别', 'Bean 生命周期与作用域（Singleton、Prototype 等）', 'Spring 事件机制与监听器', 'Spring REST —— RESTful API 设计与实现', '单元测试 —— Spring Test、MockMVC'],
    books: [
      { name: '《Spring实战》（第6版）', description: 'Craig Walls 著 · 最权威的 Spring 中文入门书，从零到实战' },
      { name: '《Spring技术内幕》', description: '计文柯 著 · 深入剖析 IoC/AOP 源码，适合进阶' },
      { name: '《精通Spring》', description: '涵盖 Spring 生态全栈，适合有一定基础后深化' },
    ],
    sites: [
      { url: 'https://docs.spring.io/spring-framework/docs/current/reference/html/', description: '官方参考文档（最权威）' },
      { url: 'https://spring.io/guides', description: '官方入门指南，包含大量实战 Demo' },
      { url: 'https://docs.spring.io/spring-framework/reference/', description: 'Spring Framework 官方参考文档新版入口' },
      { url: 'https://www.liaoxuefeng.com/wiki/1252599548343744/1266263217140032', description: '廖雪峰 Spring 教程（中文，适合入门）' },
    ],
    tip: '💡 建议先掌握 Java 基础（集合、反射、注解、多线程）再学 Spring，否则难以理解 IoC 和 AOP 的底层原理。',
  },
  {
    id: 'springboot',
    name: 'Spring Boot',
    shortName: 'Spring Boot',
    icon: '🚀',
    iconClass: 'icon-springboot',
    navIconBg: '#1a3a5c',
    category: 'web',
    categoryLabel: 'Web框架',
    subtitle: '基于 Spring 的快速开发脚手架，开箱即用，简化配置',
    frequency: 4,
    difficulty: 4,
    periodWeeks: '4–6 周（需先学 Spring）',
    periodDescription: '4–6 周（前置：Spring 基础）',
    remark: '快速构建微服务应用',
    learningOutline: [
      { title: '入门启动', items: ['Starter', '自动配置', '配置文件', '日志体系'] },
      { title: 'Web 开发', items: ['REST API', '参数校验', '异常处理', '拦截器'] },
      { title: '数据整合', items: ['MyBatis/JPA', '事务', '多环境配置', '连接池'] },
      { title: '工程能力', items: ['Actuator', '测试', '打包部署', '配置优先级'] },
      { title: '进阶应用', items: ['安全认证', '异步任务', '定时任务', '微服务基础'] },
      { title: '项目实战', items: ['后台管理系统', '统一响应', '接口文档', '部署上线'] },
    ],
    coreTopics: ['自动配置原理 —— @EnableAutoConfiguration、Condition', 'Starter 依赖体系与自定义 Starter', '配置文件体系 —— application.yml、多环境（dev/test/prod）', '内嵌服务器 —— Tomcat、Jetty、Undertow', 'Spring Boot Actuator —— 健康检查、监控指标暴露', 'Spring Boot Test —— @SpringBootTest、MockMvc、Testcontainers', '整合 MyBatis/JPA/Redis/Kafka 等中间件', 'Spring Boot 打包与部署（Jar 包、Docker 镜像）', '日志管理 —— Logback、Log4j2 配置', '异常处理 —— @ControllerAdvice、全局异常'],
    books: [
      { name: '《Spring Boot实战》（第2版）', description: 'Craig Walls 著 · 从入门到部署，理论与实战结合' },
      { name: '《深入理解Spring Boot》', description: '深入分析自动配置原理，适合有 Spring 基础者' },
      { name: '《Spring Boot + Vue全栈开发实战》', description: '涵盖前后端整合开发，适合全栈方向学习' },
    ],
    sites: [
      { url: 'https://docs.spring.io/spring-boot/docs/current/reference/html/', description: 'Spring Boot 官方参考文档' },
      { url: 'https://spring.io/projects/spring-boot', description: 'Spring Boot 项目主页与 Getting Started' },
      { url: 'https://start.spring.io', description: 'Spring Initializr —— 快速生成项目脚手架' },
      { url: 'https://docs.spring.io/spring-boot/index.html', description: 'Spring Boot 官方文档新版入口' },
    ],
    note: '📌 Spring Boot 是在 Spring 之上的封装，必须先掌握 Spring IoC、AOP、MVC 再来学习，才能真正理解“自动配置”的本质。',
  },
  {
    id: 'mybatis',
    name: 'MyBatis',
    shortName: 'MyBatis',
    icon: '🗂️',
    iconClass: 'icon-mybatis',
    navIconBg: '#4a2c0a',
    category: 'db',
    categoryLabel: '数据库',
    sectionTitle: '🗂️ 数据库层',
    subtitle: '半自动 ORM 框架，灵活的 SQL 映射，企业级主流持久层方案',
    frequency: 3,
    difficulty: 3,
    periodWeeks: '2–3 周',
    periodDescription: '2–3 周',
    remark: '主流 ORM 框架',
    learningOutline: [
      { title: 'SQL 基础巩固', items: ['CRUD', '联表查询', '索引意识', '事务概念'] },
      { title: '核心配置', items: ['SqlSession', 'Mapper', 'XML 映射', '注解映射'] },
      { title: '结果映射', items: ['resultMap', '一对一', '一对多', '懒加载'] },
      { title: '动态 SQL', items: ['if/choose', 'where/set', 'foreach', 'SQL 片段'] },
      { title: '插件与缓存', items: ['一级缓存', '二级缓存', '分页插件', '拦截器'] },
      { title: '整合实战', items: ['Spring 整合', 'Spring Boot 整合', '代码生成器', '复杂查询'] },
    ],
    coreTopics: ['SqlSessionFactory 与 SqlSession 生命周期', 'Mapper 接口与 XML 映射文件', '动态 SQL —— if、choose、where、foreach', '结果映射 —— resultMap、嵌套查询、关联查询', '缓存机制 —— 一级缓存、二级缓存', '插件机制 —— Interceptor、分页插件 PageHelper', '与 Spring / Spring Boot 整合', 'MyBatis-Plus 增强框架入门', 'SQL 性能优化与索引意识', '代码生成器使用'],
    books: [
      { name: '《MyBatis从入门到精通》', description: '刘增辉 著 · 国内最系统的 MyBatis 中文教程' },
      { name: '《Java持久化框架实战》', description: '对比 JPA、MyBatis，深入理解 ORM 体系' },
    ],
    sites: [
      { url: 'https://mybatis.org/mybatis-3/zh_CN/index.html', description: 'MyBatis 官方中文文档（首选）' },
      { url: 'https://baomidou.com/getting-started/', description: 'MyBatis-Plus 官方文档' },
      { url: 'https://pagehelper.github.io/', description: 'PageHelper 分页插件官方文档' },
    ],
  },
  {
    id: 'oracle',
    name: 'Oracle Database',
    shortName: 'Oracle',
    icon: '🔴',
    iconClass: 'icon-oracle',
    navIconBg: '#4a0a0a',
    category: 'db',
    categoryLabel: '数据库',
    subtitle: '企业级关系型数据库，与达梦（DM8）、金仓等国产数据库架构相似',
    frequency: 2,
    difficulty: 2,
    periodWeeks: '4–6 周',
    periodDescription: '4–6 周',
    remark: '与达梦、金仓等国产库类似',
    learningOutline: [
      { title: '数据库基础', items: ['表/视图', '数据类型', '约束', '索引'] },
      { title: 'SQL 查询', items: ['SELECT', 'JOIN', '子查询', '聚合函数'] },
      { title: 'Oracle 特性', items: ['序列', '同义词', '分页', '函数体系'] },
      { title: 'PL/SQL', items: ['变量', '过程', '函数', '游标'] },
      { title: '事务与性能', items: ['锁机制', '执行计划', '索引优化', 'SQL 调优'] },
      { title: '运维与迁移', items: ['用户权限', '备份恢复', '国产库兼容', '项目接入'] },
    ],
    coreTopics: ['Oracle 数据类型、表空间、用户与权限', 'SQL 查询、聚合、子查询、JOIN', '序列、视图、索引、同义词', 'PL/SQL —— 存储过程、函数、触发器', '事务、锁、隔离级别', '执行计划与 SQL 调优', '分页查询与 ROWNUM / FETCH FIRST', '备份恢复基础', '达梦、金仓与 Oracle 语法差异', 'Java 项目连接 Oracle / DM 数据库'],
    books: [
      { name: '《Oracle Database 11g/12c完全参考手册》', description: 'Kevin Loney 著 · Oracle 最权威参考手册，全面深入' },
      { name: '《Oracle高性能SQL引擎剖析》', description: '黄玮 著 · SQL 执行计划与调优进阶' },
      { name: '《循序渐进Oracle》', description: '盖国强 著 · 国内 Oracle 经典，DBA 必读' },
    ],
    sites: [
      { url: 'https://docs.oracle.com/en/database/', description: 'Oracle 官方文档中心' },
      { url: 'https://www.oracletutorial.com/', description: 'Oracle Tutorial —— 系统化英文教程' },
      { url: 'https://eco.dameng.com/document/dm/zh-cn/start/', description: '达梦数据库官方文档（可对比学习）' },
    ],
    note: '📌 Oracle 语法迁移到达梦/金仓成本较低，掌握 Oracle 可触类旁通。建议同时了解差异点（ROWNUM vs LIMIT、序列创建语法等）。',
  },
  {
    id: 'redis',
    name: 'Redis',
    shortName: 'Redis',
    icon: '⚡',
    iconClass: 'icon-redis',
    navIconBg: '#4a1010',
    category: 'cache',
    categoryLabel: '缓存',
    sectionTitle: '⚡ 缓存',
    subtitle: '高性能内存数据库，提升数据库查询效率，支持多种数据结构',
    frequency: 4,
    difficulty: 1,
    periodWeeks: '2–3 周',
    periodDescription: '2–3 周（入门容易，生产实践需积累）',
    remark: '提高数据库查询效率',
    learningOutline: [
      { title: '基础入门', items: ['安装连接', 'Key 设计', '过期策略', '持久化概念'] },
      { title: '数据结构', items: ['String', 'Hash', 'List', 'Set', 'ZSet'] },
      { title: '典型场景', items: ['缓存', '计数器', '排行榜', '分布式锁'] },
      { title: '缓存问题', items: ['穿透', '击穿', '雪崩', '一致性'] },
      { title: '高可用', items: ['主从复制', '哨兵', 'Cluster', '故障转移'] },
      { title: '项目实战', items: ['Spring Data Redis', '缓存设计', '限流', '性能压测'] },
    ],
    coreTopics: ['Redis 基础命令与客户端连接', '五大数据结构：String、Hash、List、Set、ZSet', '过期策略、淘汰策略、内存管理', '持久化 —— RDB、AOF', '缓存穿透、击穿、雪崩解决方案', '分布式锁 —— SET NX PX、Redisson', '发布订阅、Stream 消息队列', '主从复制、哨兵、Cluster 集群', '与 Spring Boot 整合 —— Spring Data Redis', '性能优化与大 Key、热 Key 治理'],
    books: [
      { name: '《Redis设计与实现》', description: '黄健宏 著 · 深入理解 Redis 底层结构，进阶必读' },
      { name: '《Redis实战》', description: 'Josiah Carlson 著 · 场景丰富，适合实战' },
      { name: '《Redis开发与运维》', description: '付磊等著 · 国内生产实践经验总结' },
    ],
    sites: [
      { url: 'https://redis.io/docs/', description: 'Redis 官方文档' },
      { url: 'https://redis.com.cn/documentation.html', description: 'Redis 中文文档' },
      { url: 'https://www.redis.io/try-free/', description: 'Redis 在线体验与云服务' },
    ],
    tip: '💡 Redis 入门很快，但生产环境重点在缓存设计、高可用、性能与一致性问题。建议结合真实业务场景学习。',
  },
  {
    id: 'maven',
    name: 'Maven',
    shortName: 'Maven',
    icon: '📦',
    iconClass: 'icon-maven',
    navIconBg: '#2a1a4a',
    category: 'build',
    categoryLabel: '构建工具',
    sectionTitle: '📦 构建工具',
    subtitle: 'Java 项目构建与依赖管理工具，后端开发必备基础设施',
    frequency: 4,
    difficulty: 0,
    periodWeeks: '1–2 周',
    periodDescription: '1–2 周（难度最低，实用为主）',
    remark: '方便管理维护项目依赖',
    learningOutline: [
      { title: '基础概念', items: ['坐标', 'POM', '仓库', '依赖声明'] },
      { title: '生命周期', items: ['clean', 'compile', 'test', 'package'] },
      { title: '依赖管理', items: ['传递依赖', '依赖冲突', 'scope', 'exclusions'] },
      { title: '插件体系', items: ['compiler', 'surefire', 'shade', 'resources'] },
      { title: '多模块项目', items: ['父子工程', '聚合', '继承', '版本统一'] },
      { title: '工程实践', items: ['私服', 'Profile', 'CI 构建', '发布流程'] },
    ],
    coreTopics: ['Maven 坐标 —— groupId、artifactId、version', 'POM 文件结构与继承关系', '依赖范围 —— compile、test、provided、runtime', '依赖传递与冲突解决 —— exclusion、dependencyManagement', 'Maven 生命周期 —— clean、validate、compile、test、package、install、deploy', '常用插件 —— maven-compiler、surefire、shade、assembly', '多模块项目管理 —— 父 POM、子模块继承', '私服搭建 —— Nexus Repository Manager', 'Maven Wrapper（mvnw）的使用', '本地仓库与中央仓库、镜像配置（阿里云镜像）', 'Profile 多环境构建'],
    books: [
      { name: '《Maven实战》', description: '许晓斌 著 · 国内最权威的 Maven 中文书' },
      { name: '《Maven: The Definitive Guide》', description: '官方免费电子书，覆盖所有特性' },
    ],
    sites: [
      { url: 'https://maven.apache.org/guides/index.html', description: 'Maven 官方指南' },
      { url: 'https://central.sonatype.com/', description: 'Maven 中央仓库搜索（查找坐标）' },
      { url: 'https://maven.apache.org/ref/current/maven-model/maven.html', description: 'POM 文件完整元素参考' },
    ],
    tip: '💡 Maven 难度最低，建议在开始 Spring 学习之前先完成 Maven 入门，能显著提升后续开发体验。',
  },
  {
    id: 'docker',
    name: 'Docker',
    shortName: 'Docker',
    icon: '🐳',
    iconClass: 'icon-docker',
    navIconBg: '#0a2a4a',
    category: 'container',
    categoryLabel: '容器',
    sectionTitle: '🐳 容器化',
    subtitle: '容器化平台，项目环境打包标准化，实现一次构建、随处运行',
    frequency: 3,
    difficulty: 3,
    periodWeeks: '3–4 周',
    periodDescription: '3–4 周',
    remark: '项目环境打包，方便部署',
    learningOutline: [
      { title: '容器基础', items: ['镜像', '容器', '仓库', 'Volume'] },
      { title: '常用命令', items: ['run', 'exec', 'logs', 'inspect'] },
      { title: '镜像构建', items: ['Dockerfile', '分层缓存', '多阶段构建', '镜像瘦身'] },
      { title: '网络与存储', items: ['bridge', '端口映射', '数据卷', 'Compose 网络'] },
      { title: '编排入门', items: ['Docker Compose', '环境变量', '服务依赖', '日志排查'] },
      { title: '项目部署', items: ['Java 应用镜像', '数据库容器', 'Nginx', '生产注意事项'] },
    ],
    coreTopics: ['Docker 核心概念 —— 镜像、容器、仓库、数据卷', '常用命令 —— run、exec、logs、inspect、cp', 'Dockerfile 编写 —— FROM、RUN、COPY、CMD、ENTRYPOINT', '镜像分层与缓存机制', 'Docker 网络 —— bridge、host、none、自定义网络', '数据卷与持久化', 'Docker Compose 多服务编排', 'Java 应用容器化 —— Spring Boot Jar 镜像', 'Nginx + 后端服务部署', '基础安全与镜像瘦身'],
    books: [
      { name: '《Docker技术入门与实战》', description: '杨保华 著 · 国内 Docker 入门经典' },
      { name: '《Docker Deep Dive》', description: 'Nigel Poulton 著 · 英文经典，系统清晰' },
    ],
    sites: [
      { url: 'https://docs.docker.com/get-started/', description: 'Docker 官方 Get Started' },
      { url: 'https://docs.docker.com/compose/', description: 'Docker Compose 官方文档' },
      { url: 'https://hub.docker.com/', description: 'Docker Hub 镜像仓库' },
      { url: 'https://www.runoob.com/docker/docker-tutorial.html', description: '菜鸟教程 Docker 中文教程' },
    ],
    note: '📌 学 Docker 时建议边学边部署一个 Spring Boot + MySQL/Redis 的小项目，理解容器网络和数据卷会更快。',
  },
  {
    id: 'kafka',
    name: 'Apache Kafka',
    shortName: 'Kafka',
    icon: '📨',
    iconClass: 'icon-kafka',
    navIconBg: '#1a3a1a',
    category: 'mq',
    categoryLabel: '消息队列',
    sectionTitle: '📨 消息队列',
    subtitle: '高吞吐分布式消息系统，适合日志采集、流处理和大数据场景',
    frequency: 1,
    difficulty: 1,
    periodWeeks: '2–3 周',
    periodDescription: '2–3 周',
    remark: '高吞吐量流处理',
    learningOutline: [
      { title: 'MQ 基础', items: ['异步', '解耦', '削峰', '发布订阅'] },
      { title: 'Kafka 架构', items: ['Broker', 'Topic', 'Partition', '副本机制'] },
      { title: '生产消费', items: ['Producer', 'Consumer', '消费者组', 'Offset'] },
      { title: '可靠性机制', items: ['acks', '幂等', '事务', '重试策略'] },
      { title: '生态能力', items: ['Kafka Streams', 'Kafka Connect', 'Schema Registry', '监控'] },
      { title: '项目实战', items: ['Spring Kafka', '日志收集', '消息积压处理', '性能调优'] },
    ],
    coreTopics: ['消息队列核心概念 —— 异步、解耦、削峰', 'Kafka 架构 —— Broker、Zookeeper/KRaft、Controller', 'Topic 与 Partition —— 分区设计、副本机制', 'Producer API —— 发送模式、分区器、序列化', 'Consumer API —— 消费者组、偏移量管理、再均衡', '消息可靠性 —— acks 配置、幂等性、事务消息', 'Kafka Streams —— 流式计算 DSL', 'Kafka Connect —— 数据集成框架', '与 Spring Boot 整合 —— spring-kafka 使用', '性能调优 —— 批量发送、压缩、消费者并发'],
    books: [
      { name: '《Kafka权威指南》（第2版）', description: 'Neha Narkhede 等著 · Kafka 经典权威书籍' },
      { name: '《Apache Kafka实战》', description: '胡夕 著 · 国内 Kafka 专家著作，中文首选' },
    ],
    sites: [
      { url: 'https://kafka.apache.org/documentation/', description: 'Kafka 官方文档' },
      { url: 'https://docs.spring.io/spring-kafka/reference/', description: 'Spring for Apache Kafka 官方文档' },
      { url: 'https://www.conduktor.io/kafka/what-is-apache-kafka/', description: 'Conduktor —— 图文并茂的 Kafka 免费教程' },
    ],
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    shortName: 'RabbitMQ',
    icon: '🐰',
    iconClass: 'icon-rabbit',
    navIconBg: '#3a2a0a',
    category: 'mq',
    categoryLabel: '消息队列',
    subtitle: '基于 AMQP 协议的企业级消息中间件，适合复杂路由与业务解耦',
    frequency: 1,
    difficulty: 1,
    periodWeeks: '2–3 周',
    periodDescription: '2–3 周',
    remark: '企业级消息中间件',
    learningOutline: [
      { title: 'MQ 基础', items: ['异步处理', '业务解耦', '削峰填谷', '可靠投递'] },
      { title: 'AMQP 模型', items: ['Connection', 'Channel', 'Exchange', 'Queue'] },
      { title: '路由模式', items: ['Direct', 'Fanout', 'Topic', 'Headers'] },
      { title: '可靠性设计', items: ['ACK/NACK', 'Publisher Confirm', '持久化', '重试'] },
      { title: '高级特性', items: ['死信队列', '延迟队列', '优先级队列', 'TTL'] },
      { title: '项目实战', items: ['Spring AMQP', '@RabbitListener', '订单异步', '集群部署'] },
    ],
    coreTopics: ['AMQP 协议核心概念 —— Connection、Channel、Virtual Host', 'Exchange 类型 —— Direct、Fanout、Topic、Headers', 'Queue 特性 —— 持久化、独占、自动删除', 'Binding 与 Routing Key 路由规则', '消息确认机制 —— 手动 ack/nack，消息重试', '死信队列（DLX）与延迟队列设计', '消息持久化与发布确认（Publisher Confirms）', '流控（Flow Control）与背压机制', 'RabbitMQ 集群与镜像队列高可用', '与 Spring Boot 整合 —— spring-amqp、@RabbitListener'],
    books: [
      { name: '《RabbitMQ实战》', description: 'Alvaro Videla 著 · 从入门到生产部署，系统全面' },
      { name: '《RabbitMQ实战指南》', description: '朱忠华 著 · 国内 RabbitMQ 专项书，中文首选' },
    ],
    sites: [
      { url: 'https://www.rabbitmq.com/docs', description: 'RabbitMQ 官方文档' },
      { url: 'https://www.rabbitmq.com/tutorials', description: 'RabbitMQ 官方入门教程（6种模式）' },
      { url: 'https://docs.spring.io/spring-amqp/reference/', description: 'Spring AMQP 官方文档' },
    ],
    tip: '💡 Kafka 和 RabbitMQ 定位不同：RabbitMQ 适合业务消息路由；Kafka 适合高吞吐日志/流处理。建议先学 RabbitMQ 更易理解 MQ 概念。',
  },
]

export const navSections: NavSection[] = [
  { title: 'Web 框架', items: techGuides.filter((item) => item.category === 'web') },
  { title: '数据库', items: techGuides.filter((item) => item.category === 'db') },
  { title: '缓存', items: techGuides.filter((item) => item.category === 'cache') },
  { title: '构建 & 容器', items: techGuides.filter((item) => item.category === 'build' || item.category === 'container') },
  { title: '消息队列', items: techGuides.filter((item) => item.category === 'mq') },
]

export const overviewRows: OverviewRow[] = techGuides.map(({ category, shortName, frequency, difficulty, periodWeeks, remark }) => ({
  category,
  name: shortName,
  frequency,
  difficulty,
  period: periodWeeks,
  remark,
}))

export const heroStats = [
  { value: techGuides.length, label: '技术项' },
  { value: new Set(techGuides.map((item) => item.category)).size, label: '技术类型' },
  { value: '28-40', label: '学习周数' },
  { value: '15+', label: '推荐书籍' },
]
